version: "3.8"

services:
  mr-studio:
    build: .
    container_name: mr-studio
    restart: unless-stopped
    ports:
      - "5002:5002"
    env_file:
      - .env
    volumes:
      - mr_studio_uploads:/app/.local/storage/uploads
    networks:
      - caddy_network

volumes:
  mr_studio_uploads:


networks:
  caddy_network:
    external: true
    name: n8n-docker-caddy_default
